apiVersion: v1
kind: Service
metadata:
  name: {{ include "current.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "current.name" . }}
    helm.sh/chart: {{ include "current.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 67
    name: dhcp
    targetPort: 67
    protocol: UDP
  selector:
    app.kubernetes.io/name: {{ include "current.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
