#requirements.yaml
dependencies:
## mandatory (no tags, but can be overridden with condition
- name: topology-builder
  version: ">=0.1"
  repository: "https://repo.snaproute.com/chartrepo/virtualization"