# Default values for 2node.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  vmsRunning: true

topology-builder:

  dhcpOptions:
    privateOptions:
    - option: 114
      value: http://192.168.105.95/onie-installer-x86_64


  # VM configuration defines the size of node and the number of ports to expose (in addition to mgmt0)
  vms:
    spine1:
      ports: 3
      vmPreset: onie-2core-8g
      diskSize: 16G

    spine2:
      ports: 3
      vmPreset: onie-2core-8g
      diskSize: 16G

    leaf1:
      ports: 4
      vmPreset: onie-2core-8g
      diskSize: 16G

    leaf2:
      ports: 4
      vmPreset: onie-2core-8g
      diskSize: 16G

    borderleaf1:
      ports: 4
      vmPreset: onie-2core-8g
      diskSize: 16G

  # Links configuration defines the mapping between switch ports (in the form <switchName>-p<portNumber>)
  links:
    spine1-p1: leaf1-p1
    spine1-p2: leaf2-p1
    spine1-p3: borderleaf1-p1
    spine2-p1: leaf1-p2
    spine2-p2: leaf2-p2
    spine2-p3: borderleaf1-p2


